PYTHON_PATH: "D:/pwn/ida9.1/python311/python.exe"
IDA_PATH: "D:/pwn/ida9.1/idat.exe"
FIXED_ELF_PATH: "C:/Users/MECHREVO/Desktop/SSTS/a/a/ssts/resource/5.0.3_fix.elf"
UNFIXED_ELF_PATH: "C:/Users/MECHREVO/Desktop/SSTS/a/a/ssts/resource/unfix_5.0.3.elf"
OPENAI_API_KEY: "sk-3bgGrIPsUpnVlVyJTomazzpxjHkCHKflOoBQaZYIvO6zb2rZ"
#OPENAI_BASE_URL: "https://free.v36.cm/v1/"
OPENAI_BASE_URL: "https://api.chatanywhere.tech/v1/"
GITCODE_PRIVATE_TOKEN: "gRrQ6x5N3Ey-EV1-ar5J-CU6"
GITHUB_TOKEN: "你的GitHub_PAT只读即可"
