"""采集能力对外入口：其他模块请从本包导入。"""

from autoyara.collectors import (
    UPSTREAM,
    apply_collector_config,
    classify_url,
    collect_cve_items,
    extract_function,
    fetch_bulletin,
    fetch_diff_text,
    fetch_gitcode_commit_diff,
    fetch_gitcode_file_blob,
    fetch_source,
    fetch_vuln_description,
    get,
    get_parent_sha,
    get_upstream_commit_from_patch,
    gitcode_private_token,
    links_from_config,
    normalize_gitcode_diff_body,
    parse_all_links,
    parse_diff_full,
    parse_vuln_desc_from_patch_text,
    pick_best_pr_commit_diff,
    process_item,
)
from autoyara.models import CollectorConfig, CVEItem, CVEResult

__all__ = [
    "CollectorConfig",
    "CVEItem",
    "CVEResult",
    "apply_collector_config",
    "collect_cve_items",
    "links_from_config",
    "UPSTREAM",
    "classify_url",
    "extract_function",
    "fetch_bulletin",
    "fetch_diff_text",
    "fetch_gitcode_commit_diff",
    "fetch_gitcode_file_blob",
    "fetch_source",
    "fetch_vuln_description",
    "get",
    "get_parent_sha",
    "get_upstream_commit_from_patch",
    "gitcode_private_token",
    "normalize_gitcode_diff_body",
    "parse_all_links",
    "parse_diff_full",
    "parse_vuln_desc_from_patch_text",
    "pick_best_pr_commit_diff",
    "process_item",
]
